//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ads.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudio
    {
        public estudio()
        {
            this.pacientes_estudios = new HashSet<pacientes_estudios>();
        }
    
        public int cod_estudio { get; set; }
        public string desc_estudio { get; set; }
        public int estado_estudio { get; set; }
    
        public virtual ICollection<pacientes_estudios> pacientes_estudios { get; set; }
    }
}
