//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ads.EntityFrameWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Ads.DataAcces;
    using System.Linq;
    using System.Collections.Generic;

    public partial class dialisisEntities : DbContext, IContext
    {
        public dialisisEntities()
            : base("name=dialisisEntities")
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            if (modelBuilder == null)
            {
                throw new ArgumentNullException("modelBuilder");
            }

            base.OnModelCreating(modelBuilder);

        }


        public virtual DbSet<accesovascular> accesovasculars { get; set; }
        public virtual DbSet<estudio> estudios { get; set; }
        public virtual DbSet<localizacionanastomosi> localizacionanastomosis { get; set; }
        public virtual DbSet<motivobaja> motivobajas { get; set; }
        public virtual DbSet<obrasocial> obrasocials { get; set; }
        public virtual DbSet<observacione> observaciones { get; set; }
        public virtual DbSet<paciente_ioma> paciente_ioma { get; set; }
        public virtual DbSet<paciente_pami> paciente_pami { get; set; }
        public virtual DbSet<paciente> pacientes { get; set; }
        public virtual DbSet<pacientes_estudios> pacientes_estudios { get; set; }
        public virtual DbSet<tipoanastomosi> tipoanastomosis { get; set; }
        public virtual DbSet<vacuna_paciente> vacuna_paciente { get; set; }
        public virtual DbSet<vacuna> vacunas { get; set; }


        public T GetById<T>(int id) where T : class
        {

            return base.Set<T>().Find(id);
        }

        public void Add<T>(T entity) where T : class
        {
            base.Set<T>().Add(entity);
            base.SaveChanges();

        }

        public void Delete<T>(T entity) where T : class
        {
            throw new NotImplementedException();
        }

        public void SaveOrUpdate()
        {
            base.SaveChanges();
        }

        public IQueryable<T> Query<T>() where T : class
        {
            return Set<T>();
        }

    }
}
