//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ads.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class observacione
    {
        public int cod_paciente { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual paciente paciente { get; set; }
    }
}
