//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ads.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class paciente
    {
        public paciente()
        {
            this.accesovasculars = new HashSet<accesovascular>();
            this.observaciones = new HashSet<observacione>();
            this.paciente_ioma = new HashSet<paciente_ioma>();
            this.paciente_pami = new HashSet<paciente_pami>();
            this.vacuna_paciente = new HashSet<vacuna_paciente>();
            this.pacientes_estudios = new HashSet<pacientes_estudios>();
        }
    
        public int cod_paciente { get; set; }
        public string nombre { get; set; }
        public string Apellido { get; set; }
        public string obraSocial { get; set; }
        public string sexo { get; set; }
        public string diabetes { get; set; }
        public Nullable<decimal> altura { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string epo { get; set; }
        public Nullable<int> dosis { get; set; }
        public string estado { get; set; }
        public string nroObraSocial { get; set; }
        public Nullable<System.DateTime> fechaPrimer { get; set; }
        public string etiologico { get; set; }
        public string incucai { get; set; }
        public string antecedente { get; set; }
        public string turno { get; set; }
        public Nullable<System.DateTime> fechacreacionav { get; set; }
        public Nullable<System.DateTime> fechaprimerusoav { get; set; }
        public Nullable<int> cod_anastomosis { get; set; }
        public Nullable<int> cod_localizacionanastomosis { get; set; }
        public Nullable<int> cantavanteriores { get; set; }
        public Nullable<System.DateTime> fechaprimervida { get; set; }
        public Nullable<System.DateTime> fechaprimeros { get; set; }
        public Nullable<int> codmotivobaja { get; set; }
        public string descmotivobaja { get; set; }
        public Nullable<System.DateTime> fechabaja { get; set; }
        public Nullable<int> id_os { get; set; }
        public string domicilio { get; set; }
        public string localidad { get; set; }
        public string telefono { get; set; }
        public string grupo_sang { get; set; }
        public string cirugias_prev { get; set; }
        public Nullable<bool> infeccionesUrinarias { get; set; }
        public Nullable<System.DateTime> diabetes_fechaDesde { get; set; }
        public Nullable<bool> hematuria { get; set; }
        public Nullable<bool> litasisRenal { get; set; }
        public Nullable<bool> nonturia { get; set; }
        public Nullable<bool> hipertension { get; set; }
        public Nullable<System.DateTime> hip_tiempoevol { get; set; }
        public string hip_tratamiento { get; set; }
    
        public virtual ICollection<accesovascular> accesovasculars { get; set; }
        public virtual localizacionanastomosi localizacionanastomosi { get; set; }
        public virtual motivobaja motivobaja { get; set; }
        public virtual obrasocial obrasocial1 { get; set; }
        public virtual ICollection<observacione> observaciones { get; set; }
        public virtual ICollection<paciente_ioma> paciente_ioma { get; set; }
        public virtual ICollection<paciente_pami> paciente_pami { get; set; }
        public virtual tipoanastomosi tipoanastomosi { get; set; }
        public virtual ICollection<vacuna_paciente> vacuna_paciente { get; set; }
        public virtual ICollection<pacientes_estudios> pacientes_estudios { get; set; }
    }
}
